### ISSUE TITLE
Design Todo List and Item Model

### ISSUE THREAD

**Issue by zachbharris** [zachbharris/Daily#2]
We need to have a rough design of what our `List` and `ListItem` object models will look like.

# Requirements

## List

- [x] Should have a property that stores all of its `ListItem[]` children
- [x] Should have `createdAt: Date`, `updatedAt: Date` and `deletedAt: Date` columns

```ts
type List = {
  id: String
  items: ListItem[]
  createdAt: Date
  updatedAt: Date
  deletedAt: Date
}
```

## List Item

- [x] Must have a `listId` property that references its parent `List`
- [x] Should a row called `content: string[]` that contains the item string content
- [x] Should have `createdAt: Date`, `updatedAt: Date` and `deletedAt: Date` columns
- [x] Must have a `isComplete: boolean` column

```ts
type ListItem = {
  id: String
  listId: String
  content: String[]
  isComplete: Boolean
  createdAt: Date
  updatedAt: Date
  deletedAt: Date
}
```
